data(ToothGrowth)
head(ToothGrowth)
tg.m <-tapply(ToothGrowth$len,ToothGrowth$dose,mean)
tg.sd <-tapply(ToothGrowth$len,ToothGrowth$dose,sd)
tg<-cbind(tg.m,tg.sd)
tg<-as.data.frame(tg)
tg$Dose <- c(0.5,1,2)
par(mgp=c(1.6,0.6,0))
bp<- barplot(tg.m,xlab = "Dose", ylab = "Growth", cex.lab = 1.5,ylim=c(0,35),space=2,col=1)
arrows(bp,tg.m,bp,tg.m+tg.sd,lwd=1.5,angle=90,length=0.1)
box()
